server:
  port: 8081

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: file:///D:/workspace-idea/spring-cloud-readhub-config
  security:
    basic:
      enabled: true
    user:
      name: user
      password: secret
